/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tehyn.tech.pos;

import javax.swing.*;

/**
 *
 * @author THULEBONA
 */
public class add_edit_staff extends JDialog {

    /**
     * Creates new form add_edit_staff
     * @param popup
     */
    public add_edit_staff(main_Screen popup) {
        super(popup,true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffnumlbl = new javax.swing.JLabel();
        staffNumbertxt = new javax.swing.JTextField();
        staffNamelbl = new javax.swing.JLabel();
        staffNametxt = new javax.swing.JTextField();
        staffSurnamelbl = new javax.swing.JLabel();
        staffSurnametxt = new javax.swing.JTextField();
        staffUsernamelbl = new javax.swing.JLabel();
        staffUsernametxt = new javax.swing.JTextField();
        staffuserPasswordlbl = new javax.swing.JLabel();
        staffuserPasswordtxt = new javax.swing.JTextField();
        addStaffsaveBtn = new javax.swing.JButton();
        addStaffCancel = new javax.swing.JButton();
        staffconfPasswordlbl = new javax.swing.JLabel();
        staffuserPasswordtxt1 = new javax.swing.JTextField();

        setType(java.awt.Window.Type.POPUP);

        staffnumlbl.setText("Staff Number: ");

        staffNamelbl.setText("Staff Name: ");

        staffSurnamelbl.setText("Staff Surname: ");

        staffUsernamelbl.setText("Staff Username: ");

        staffuserPasswordlbl.setText("User Password: ");

        addStaffsaveBtn.setText("Save");

        addStaffCancel.setText("Cancel");
        addStaffCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffCancelActionPerformed(evt);
            }
        });

        staffconfPasswordlbl.setText("Conferm Password: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStaffsaveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(addStaffCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(staffnumlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(staffNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(staffSurnamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(staffUsernamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(staffuserPasswordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(staffconfPasswordlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staffNametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffSurnametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffUsernametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffuserPasswordtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffuserPasswordtxt1)
                            .addComponent(staffNumbertxt))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffnumlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffSurnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffSurnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffUsernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffuserPasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffuserPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffconfPasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffuserPasswordtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffsaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_addStaffCancelActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffCancel;
    private javax.swing.JButton addStaffsaveBtn;
    private javax.swing.JLabel staffNamelbl;
    private javax.swing.JTextField staffNametxt;
    private javax.swing.JTextField staffNumbertxt;
    private javax.swing.JLabel staffSurnamelbl;
    private javax.swing.JTextField staffSurnametxt;
    private javax.swing.JLabel staffUsernamelbl;
    private javax.swing.JTextField staffUsernametxt;
    private javax.swing.JLabel staffconfPasswordlbl;
    private javax.swing.JLabel staffnumlbl;
    private javax.swing.JLabel staffuserPasswordlbl;
    private javax.swing.JTextField staffuserPasswordtxt;
    private javax.swing.JTextField staffuserPasswordtxt1;
    // End of variables declaration//GEN-END:variables
}
